#!/bin/sh
#
. ./dot_env

#MACRO mytunes
sixdesktunes
#MACRO mytunes

# And now we have a new loop over the tunescans
itunexx=$itunex
ituneyy=$ituney
if test "$ideltax" -eq 0 -a "$ideltay" -eq 0
then
  ideltax=1000000
  ideltay=1000000
fi
while test "$itunexx" -le "$itunex1" -o "$ituneyy" -le "$ituney1"
do
  # returns tunexx/tuneyy, computed from itunexx/ituneyy,
  #    using xlen/ylen
  sixdeskPrepareTunes
  sixdesktunes=$tunexx"_"$tuneyy
  echo "Tunes $sixdesktunes"
  s=$istamad
  while test "$s" -le $iendmad
  do
    echo "Seed $s"
    cat $sixdesktrack/$LHCDescrip/$s/simul/$sixdesktunes/betavalues
    s=`expr $s + 1`
  done
  itunexx=`expr $itunexx + $ideltax`
  ituneyy=`expr $ituneyy + $ideltay`
done
