#!/bin/sh

#################
## Definitions ##
#################

export SixDeskDev="/afs/cern.ch/work/p/phermes/private/SixDesk/utilities/bash"
export MADbasedir="/afs/cern.ch/work/p/phermes/private/161207_MBH_TF/sixtrack_input/"



# name of the mother mask file (without extension .mask)

export mask_prefix="test01"

# definitions to scan over octupole current and chromaticity

# logical switches

export scan_chroma=true          # scan over chromaticity
export scan_octupoles=true       # scan over octupole current


# define the points in scan to be considered

export SCAN_QP="0.0 2.0"     
export SCAN_OC="0.0 4.0"


# scan over specific mask files (which have to be existing)

scan_masks=false

export mask_names="HLLHC_B2_noMBH_inj2 HLLHC_B2_wiMBH_inj2"
export mask_names="HLLHC_B2_wiMBH_inj2"


