#!/bin/sh

#################
## Definitions ##
#################

export SixDeskDev="/afs/cern.ch/work/p/phermes/private/SixDesk/utilities/bash"
export MADbasedir="/afs/cern.ch/work/p/phermes/private/161207_MBH_TF/sixtrack_input/"



# name of the mother mask file (without extension .mask)

export mask_prefix="test01"

# definitions to scan over octupole current and chromaticity

# logical switches

#export scan_chroma=true          # scan over chromaticity
#export scan_octupoles=true       # scan over octupole current

export lscan_var1=false
export lscan_var2=false
export lscan_var3=false
export lscan_var4=false

# different variables to be looped over
# note that the corresponding variables in the MAD-X mask file must be names accordingly
# e.g. if scan_var1="QP", the chromaticity in the mask file must be assigned to %QPV
# if the logical switch is off, the variable will not be taken into account

export scan_var1="QP"                 
export scan_var2="OC"              
export scan_var3="B3"
export scan_var4="QX"


# define the variables in scan to be considered
# different types of input can be given (see below)

export scan_var1_vals=$(seq 1 10)
export scan_var2_vals=$(seq 1 10)
export scan_var3_vals=$(seq 1 10)
export scan_var4_vals=$(seq 1 10)

#export SCAN_OC="0.0 4.0"


# scan over specific mask files (which have to be existing)

scan_masks=false

export mask_names="HLLHC_B2_noMBH_inj2 HLLHC_B2_wiMBH_inj2"
export mask_names="HLLHC_B2_wiMBH_inj2"


